#!/usr/bin/python
import smtplib

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from_email = "ecaytrade.search@gmail.com"
from_name = "Ecaytrade Search <" + from_email + ">"
to_email = "steve.lorimer@gmail.com"

msg = MIMEMultipart('alternative')
msg['Subject'] = "Link"
msg['From'] = from_name
msg['To'] = to_email

html = """\
<html>
  <head></head>
  <body>
    <p>
        {}!<br>
        How are you?<br>
        Here is the <a href="https://www.python.org">link</a> you wanted.
        <img src="http://static.squarespace.com/static/511175b1e4b0c73df72b5b07/t/511178e4e4b0089580775a19/1360099556547/1920x1080-Cayman-Islands-Airborne.jpg" width="800" height="600">
    </p>
  </body>
</html>
""".format("hello")

msg.attach(MIMEText(html, 'html'))

gmail_user = from_email
with open ("password", "r") as password:
    gmail_pwd = password.read().replace('\n', '')

s = smtplib.SMTP("smtp.gmail.com",587)
s.ehlo()
s.starttls()
s.ehlo
s.login(gmail_user, gmail_pwd)
s.sendmail(from_name, to_email, msg.as_string())
s.quit()
